---
- include: python.yml

- include: network_netplan.yml

  
- name: Provision host
  become: true
  hosts: all

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
      when: hostname is defined
